# Generated by Django 4.2.7 on 2023-11-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimeFinancialTimeSeries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationMatrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correlation_from', models.CharField(max_length=200)),
                ('correlation_to', models.CharField(max_length=200)),
                ('correlation_coefficient', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
